# Generated by Django 6.0.3 on 2026-03-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(db_index=True, unique=True)),
                ('battle_id_api', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('zone', models.CharField(db_index=True, max_length=200)),
                ('total_kill_fame', models.BigIntegerField(default=0)),
                ('number_of_participants', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='battles.battle')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills_as_killer', to='players.player')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths_as_victim', to='players.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.FloatField(default=0)),
                ('healing_done', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['zone', 'timestamp'], name='events_even_zone_79e28e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'player')},
        ),
    ]
