# Generated by Django 6.0.3 on 2026-03-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_players', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_guilds', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('elo_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['is_valid', 'processed'], name='battles_bat_is_vali_43d841_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerBattleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.BigIntegerField(default=0)),
                ('healing_done', models.BigIntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('kill_fame', models.BigIntegerField(default=0)),
                ('raw_score', models.FloatField(default=0)),
                ('normalized_score', models.FloatField(default=0)),
                ('elo_before', models.IntegerField(blank=True, null=True)),
                ('elo_after', models.IntegerField(blank=True, null=True)),
                ('elo_change', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='battles.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_stats', to='players.player')),
            ],
            options={
                'ordering': ['-raw_score'],
                'unique_together': {('battle', 'player')},
            },
        ),
    ]
