# Generated by Django 6.0.3 on 2026-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbattlestats',
            name='main_weapon',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='playerbattlestats',
            name='role',
            field=models.CharField(choices=[('DPS', 'DPS'), ('HEALER', 'Healer'), ('TANK', 'Tank'), ('SUPPORT', 'Support')], default='DPS', max_length=10),
        ),
    ]
