# Generated by Django 6.0.3 on 2026-03-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_playerbattlestats_main_weapon_playerbattlestats_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbattlestats',
            name='average_item_power',
            field=models.FloatField(default=0),
        ),
    ]
