# Generated by Django 6.0.3 on 2026-03-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('guild', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FightParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TANK', 'Tanque'), ('HEALER', 'Healer'), ('SUPPORT', 'Soporte'), ('DPS', 'DPS')], max_length=10)),
                ('kill_fame', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('healing_done', models.PositiveIntegerField(default=0)),
                ('damage_done', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('elo_before', models.IntegerField(default=0)),
                ('elo_after', models.IntegerField(default=0)),
                ('performance_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rankings.fight')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='rankings.player')),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('fight', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TANK', 'Tanque'), ('HEALER', 'Healer'), ('SUPPORT', 'Soporte'), ('DPS', 'DPS')], max_length=10)),
                ('elo', models.IntegerField(default=1200)),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('peak_elo', models.IntegerField(default=1200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elos', to='rankings.player')),
            ],
            options={
                'ordering': ['-elo'],
                'unique_together': {('player', 'role')},
            },
        ),
    ]
