# Generated by Django 6.0.3 on 2026-03-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albion_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('guild_name', models.CharField(blank=True, default='', max_length=100)),
                ('guild_id', models.CharField(blank=True, default='', max_length=64)),
                ('alliance_name', models.CharField(blank=True, default='', max_length=100)),
                ('alliance_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
